# Generated by Django 3.0.5 on 2020-04-16 14:35

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='WagtailCookieConsent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Give it a name to identify the cookie. The given name will be converted to underscore naming convention to set and retrieve cookies.', max_length=255, verbose_name='Cookie Name')),
                ('banner_text', wagtail.core.fields.RichTextField(help_text='The text that appears next to the Accept button. For example: `We use cookie to give you a better experience...`', verbose_name='Banner Text')),
                ('description', wagtail.core.fields.RichTextField(help_text='Enter a detailed description of what EXACTLY are we tracking using this cookie and used by whom (For example: Google analytics). This information will be shown via a `What we are tracking` link be listed at the bottom of the acceptance banner for the end-user if they choose to read more. ')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
