# Generated by Django 3.0.5 on 2020-05-05 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcookieconsent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wagtailcookieconsent',
            name='expiration',
            field=models.PositiveIntegerField(default=30, help_text='Enter the number of days before the consent is expired. This will ', verbose_name='Cookie Expiration in Days'),
        ),
    ]
